version: 2
updates:
  - package-ecosystem: 'npm'
    # The location of the package manifests (package.json)
    directory: '/'
    target-branch: 'develop'
    versioning-strategy: 'increase'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Canada/Pacific'
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: 'build'
    reviewers:
      - 'nishiki-tech/frontend-reviewer'

  - package-ecosystem: 'github-actions'
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: '/'
    target-branch: 'develop'
    versioning-strategy: 'increase'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Canada/Pacific'
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: 'ci'
    reviewers:
      - 'nishiki-tech/frontend-reviewer'
