version: '3'
services:
  prism:
    image: stoplight/prism:5
    command: mock -h 0.0.0.0 https://raw.githubusercontent.com/genesis-tech-tribe/nishiki-documents/c1ea7d5a2fd12e1271551fc672b7141f5777ffdf/web-api/nishiki-web-api.yaml
    ports:
      # Serve the mocked API locally as available on port 8080
      - '8080:4010'
